
      // 
      // Javascript generated by HTML2 Toolkit plugin
      // 
      var tree;
      
      function treeInit() {
      tree = new YAHOO.widget.TreeView("treeDiv1");
      var root = tree.getRoot();

      
var objd63e6611 = {
  label: " DITA For Publishers User Guide",
  href: "user_docs/d4p-users-guide/frontmatter/coverpage.html", 
  target:"contentwin"
};
var d63e6611 = new YAHOO.widget.TextNode(objd63e6611, root, false);

var objd63e6641 = {
  label: " About This Book",
  href: "user_docs/d4p-users-guide/topics/about-this-book.html", 
  target:"contentwin"
};
var d63e6641 = new YAHOO.widget.TextNode(objd63e6641, root, false);

var objd63e6671 = {
  label: " Release Notes",
  href: "user_docs/d4p-users-guide/release-notes/release-notes.html", 
  target:"contentwin"
};
var d63e6671 = new YAHOO.widget.TextNode(objd63e6671, root, false);

var objd63e6703 = {
  label: " Release Notes: Version 1.0.0RC20",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0RC20.html", 
  target:"contentwin"
};
var d63e6703 = new YAHOO.widget.TextNode(objd63e6703, d63e6671, false);

var objd63e6747 = {
  label: " Release Notes: Version 1.0.0RC19",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0RC19.html", 
  target:"contentwin"
};
var d63e6747 = new YAHOO.widget.TextNode(objd63e6747, d63e6671, false);

var objd63e6791 = {
  label: " Release Notes: Version 1.0.0RC17",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0RC17.html", 
  target:"contentwin"
};
var d63e6791 = new YAHOO.widget.TextNode(objd63e6791, d63e6671, false);

var objd63e6835 = {
  label: " Release Notes: Version 1.0.0RC00 (github version)",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0.html", 
  target:"contentwin"
};
var d63e6835 = new YAHOO.widget.TextNode(objd63e6835, d63e6671, false);

var objd63e6879 = {
  label: " Release Notes: Version 0.9.19RC12",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.19.html", 
  target:"contentwin"
};
var d63e6879 = new YAHOO.widget.TextNode(objd63e6879, d63e6671, false);

var objd63e6923 = {
  label: " Release Notes: Version 0.9.18",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.18.html", 
  target:"contentwin"
};
var d63e6923 = new YAHOO.widget.TextNode(objd63e6923, d63e6671, false);

var objd63e6967 = {
  label: " Release Notes: Version 0.9.16",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.16.html", 
  target:"contentwin"
};
var d63e6967 = new YAHOO.widget.TextNode(objd63e6967, d63e6671, false);

var objd63e7011 = {
  label: " Release Notes: Version 0.9.15",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.15.html", 
  target:"contentwin"
};
var d63e7011 = new YAHOO.widget.TextNode(objd63e7011, d63e6671, false);

var objd63e7055 = {
  label: " Release Notes: Version 0.9.14",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.14.html", 
  target:"contentwin"
};
var d63e7055 = new YAHOO.widget.TextNode(objd63e7055, d63e6671, false);

var objd63e7099 = {
  label: " Release Notes: Version 0.9.13",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.13.html", 
  target:"contentwin"
};
var d63e7099 = new YAHOO.widget.TextNode(objd63e7099, d63e6671, false);

var objd63e7144 = {
  label: " Release Notes: Version 0.9.12",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.12.html", 
  target:"contentwin"
};
var d63e7144 = new YAHOO.widget.TextNode(objd63e7144, d63e6671, false);

var objd63e7188 = {
  label: " Release Notes: Version 0.9.11",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.11.html", 
  target:"contentwin"
};
var d63e7188 = new YAHOO.widget.TextNode(objd63e7188, d63e6671, false);

var objd63e7232 = {
  label: " Release Notes: Version 0.9.10",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.10.html", 
  target:"contentwin"
};
var d63e7232 = new YAHOO.widget.TextNode(objd63e7232, d63e6671, false);

var objd63e7276 = {
  label: " Release Notes: Version 0.9.9",
  href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.9.html", 
  target:"contentwin"
};
var d63e7276 = new YAHOO.widget.TextNode(objd63e7276, d63e6671, false);

var objd63e7321 = {
  label: "Chapter 1.  Introduction to DITA For Publishers",
  href: "user_docs/d4p-users-guide/topics/intro-to-d4p.html", 
  target:"contentwin"
};
var d63e7321 = new YAHOO.widget.TextNode(objd63e7321, root, false);

var objd63e7351 = {
  label: "Part I.  The DITA For Publishers Open Toolkit Plugins",
  href: "user_docs/d4p-users-guide/introduction-chapter.html", 
  target:"contentwin"
};
var d63e7351 = new YAHOO.widget.TextNode(objd63e7351, root, false);

var objd63e7381 = {
  label: "Chapter 2.  Installing the Toolkit Plugins",
  href: "user_docs/d4p-users-guide/tasks/plugin-installation.html", 
  target:"contentwin"
};
var d63e7381 = new YAHOO.widget.TextNode(objd63e7381, d63e7351, false);

var objd63e7425 = {
  label: " Setting Up The kindlegen Command-Line Utility",
  href: "user_docs/d4p-users-guide/epub-plugin/setting-up-kindlegen.html", 
  target:"contentwin"
};
var d63e7425 = new YAHOO.widget.TextNode(objd63e7425, d63e7381, false);

var objd63e7481 = {
  label: "Chapter 3.  Generating EPUBs and Kindle Books from DITA Content",
  href: "user_docs/d4p-users-guide/epub-plugin/generating-epubs.html", 
  target:"contentwin"
};
var d63e7481 = new YAHOO.widget.TextNode(objd63e7481, d63e7351, false);

var objd63e7525 = {
  label: " Generating EPUBs From OxygenXML",
  href: "user_docs/d4p-users-guide/epub-plugin/generating-epubs-from-oxygen.html", 
  target:"contentwin"
};
var d63e7525 = new YAHOO.widget.TextNode(objd63e7525, d63e7481, false);

var objd63e7581 = {
  label: " Generating Kindle Books From OxygenXML",
  href: "user_docs/d4p-users-guide/epub-plugin/generating-kindle-books-from-oxygen.html", 
  target:"contentwin"
};
var d63e7581 = new YAHOO.widget.TextNode(objd63e7581, d63e7481, false);

var objd63e7637 = {
  label: " Using Custom CSS Style Sheets",
  href: "user_docs/d4p-users-guide/epub-plugin/using-custom-css.html", 
  target:"contentwin"
};
var d63e7637 = new YAHOO.widget.TextNode(objd63e7637, d63e7481, false);

var objd63e7693 = {
  label: " Creating Cover Graphics and Covers",
  href: "user_docs/d4p-users-guide/epub-plugin/creating-cover-graphics.html", 
  target:"contentwin"
};
var d63e7693 = new YAHOO.widget.TextNode(objd63e7693, d63e7481, false);

var objd63e7749 = {
  label: " Creating Arbitrary EPUB OPF Metadata",
  href: "user_docs/d4p-users-guide/epub-plugin/creating-opf-metadata.html", 
  target:"contentwin"
};
var d63e7749 = new YAHOO.widget.TextNode(objd63e7749, d63e7481, false);

var objd63e7803 = {
  label: " Implementing Overrides for Common Processing",
  href: "user_docs/d4p-users-guide/epub-plugin/overriding-base-processing.html", 
  target:"contentwin"
};
var d63e7803 = new YAHOO.widget.TextNode(objd63e7803, d63e7481, false);

var objd63e7862 = {
  label: " Embedding Fonts in Your EPUB",
  href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
  target:"contentwin"
};
var d63e7862 = new YAHOO.widget.TextNode(objd63e7862, d63e7481, false);

var objd63e7918 = {
  label: " EPUB and Kindle Transformation Parameters",
  href: "user_docs/d4p-users-guide/epub-plugin/epub-transtype-parameters-ref.html", 
  target:"contentwin"
};
var d63e7918 = new YAHOO.widget.TextNode(objd63e7918, d63e7481, false);

var objd63e7974 = {
  label: " cover.graphic.file Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-coverGraphicFile.html", 
  target:"contentwin"
};
var d63e7974 = new YAHOO.widget.TextNode(objd63e7974, d63e7918, false);

var objd63e8043 = {
  label: " d4p.epubtype Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-epubtype.html", 
  target:"contentwin"
};
var d63e8043 = new YAHOO.widget.TextNode(objd63e8043, d63e7918, false);

var objd63e8112 = {
  label: " d4p.max.nav.depth Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-d4pMaxNavDepth.html", 
  target:"contentwin"
};
var d63e8112 = new YAHOO.widget.TextNode(objd63e8112, d63e7918, false);

var objd63e8181 = {
  label: " d4p.max.toc.depth Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-d4pMaxTocDepth.html", 
  target:"contentwin"
};
var d63e8181 = new YAHOO.widget.TextNode(objd63e8181, d63e7918, false);

var objd63e8250 = {
  label: " epub.exclude.auto.rellinks Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-epubIncludeAutoRellinks.html", 
  target:"contentwin"
};
var d63e8250 = new YAHOO.widget.TextNode(objd63e8250, d63e7918, false);

var objd63e8319 = {
  label: " epub.copy.system.css Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-epub-copy-system-css.html", 
  target:"contentwin"
};
var d63e8319 = new YAHOO.widget.TextNode(objd63e8319, d63e7918, false);

var objd63e8388 = {
  label: " epub.font.manifest Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-epub-font-manifest.html", 
  target:"contentwin"
};
var d63e8388 = new YAHOO.widget.TextNode(objd63e8388, d63e7918, false);

var objd63e8457 = {
  label: " epub.fonts.output.dir Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-epub-font-output-dir.html", 
  target:"contentwin"
};
var d63e8457 = new YAHOO.widget.TextNode(objd63e8457, d63e7918, false);

var objd63e8526 = {
  label: " epub.pubid.uri.stub Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-epubPubidUriStub.html", 
  target:"contentwin"
};
var d63e8526 = new YAHOO.widget.TextNode(objd63e8526, d63e7918, false);

var objd63e8595 = {
  label: " epub.obfuscate.fonts Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-d4p.obfuscate.fonts.html", 
  target:"contentwin"
};
var d63e8595 = new YAHOO.widget.TextNode(objd63e8595, d63e7918, false);

var objd63e8665 = {
  label: " epub.generate.css.font.rules Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-d4p.generate-css-font-rules.html", 
  target:"contentwin"
};
var d63e8665 = new YAHOO.widget.TextNode(objd63e8665, d63e7918, false);

var objd63e8734 = {
  label: " epub.temp.dir Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-epubTempDir.html", 
  target:"contentwin"
};
var d63e8734 = new YAHOO.widget.TextNode(objd63e8734, d63e7918, false);

var objd63e8803 = {
  label: " images.output.dir Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-imagesOutputDir.html", 
  target:"contentwin"
};
var d63e8803 = new YAHOO.widget.TextNode(objd63e8803, d63e7918, false);

var objd63e8872 = {
  label: " kindlegen.executable Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-kindleGenExecutable.html", 
  target:"contentwin"
};
var d63e8872 = new YAHOO.widget.TextNode(objd63e8872, d63e7918, false);

var objd63e8941 = {
  label: " title.only.topic.class.spec Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-titleOnlyTopicClassSpec.html", 
  target:"contentwin"
};
var d63e8941 = new YAHOO.widget.TextNode(objd63e8941, d63e7918, false);

var objd63e9010 = {
  label: " title.only.topic.title.class.spec Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-titleOnlyTopicTitleClassSpec.html", 
  target:"contentwin"
};
var d63e9010 = new YAHOO.widget.TextNode(objd63e9010, d63e7918, false);

var objd63e9079 = {
  label: " topics.output.dir Ant parameter",
  href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-topicsOutputDir.html", 
  target:"contentwin"
};
var d63e9079 = new YAHOO.widget.TextNode(objd63e9079, d63e7918, false);

var objd63e9148 = {
  label: "Chapter 4.  Map-Driven Processing",
  href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
  target:"contentwin"
};
var d63e9148 = new YAHOO.widget.TextNode(objd63e9148, d63e7351, false);

var objd63e9192 = {
  label: " Data Collection Processing Phase",
  href: "user_docs/d4p-users-guide/map-driven-processing/data-collection.html", 
  target:"contentwin"
};
var d63e9192 = new YAHOO.widget.TextNode(objd63e9192, d63e9148, false);

var objd63e9248 = {
  label: " Numbering Things: Collected Data and Enumeration",
  href: "user_docs/d4p-users-guide/map-driven-processing/enumeration.html", 
  target:"contentwin"
};
var d63e9248 = new YAHOO.widget.TextNode(objd63e9248, d63e9148, false);

var objd63e9304 = {
  label: " Index Generation",
  href: "user_docs/d4p-users-guide/map-driven-processing/index-generation.html", 
  target:"contentwin"
};
var d63e9304 = new YAHOO.widget.TextNode(objd63e9304, d63e9148, false);

var objd63e9360 = {
  label: " Graphic Map Generation",
  href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
  target:"contentwin"
};
var d63e9360 = new YAHOO.widget.TextNode(objd63e9360, d63e9148, false);

var objd63e9416 = {
  label: "Chapter 5.  HTML2 Plugin",
  href: "user_docs/d4p-users-guide/html2-plugin/html2-toolkit-plugin.html", 
  target:"contentwin"
};
var d63e9416 = new YAHOO.widget.TextNode(objd63e9416, d63e7351, false);

var objd63e9460 = {
  label: " Understanding the HTML2 Transformations",
  href: "user_docs/d4p-users-guide/html2-plugin/understanding-html2-transforms.html", 
  target:"contentwin"
};
var d63e9460 = new YAHOO.widget.TextNode(objd63e9460, d63e9416, false);

var objd63e9516 = {
  label: " Overall HTML Generation Process Flow",
  href: "user_docs/d4p-users-guide/html2-plugin/overall-process-flow.html", 
  target:"contentwin"
};
var d63e9516 = new YAHOO.widget.TextNode(objd63e9516, d63e9460, false);

var objd63e9585 = {
  label: " Extending and Customizing Enumeration Processing (Numbering)",
  href: "user_docs/d4p-users-guide/html2-plugin/customizing-enumeration.html", 
  target:"contentwin"
};
var d63e9585 = new YAHOO.widget.TextNode(objd63e9585, d63e9460, false);

var objd63e9654 = {
  label: " Using collected-data ",
  href: "user_docs/d4p-users-guide/topics/using-collected-data.html", 
  target:"contentwin"
};
var d63e9654 = new YAHOO.widget.TextNode(objd63e9654, d63e9585, false);

var objd63e9733 = {
  label: " HTML2 Transformation Parameters",
  href: "user_docs/d4p-users-guide/html2-plugin/html2-transtype-parameters-ref.html", 
  target:"contentwin"
};
var d63e9733 = new YAHOO.widget.TextNode(objd63e9733, d63e9416, false);

var objd63e9789 = {
  label: " html2.file.organization.strategy Ant parameter",
  href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-fileOrganizationStrategy.html", 
  target:"contentwin"
};
var d63e9789 = new YAHOO.widget.TextNode(objd63e9789, d63e9733, false);

var objd63e9858 = {
  label: " html2.generate.dynamic.toc Ant parameter",
  href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateDynamicToc.html", 
  target:"contentwin"
};
var d63e9858 = new YAHOO.widget.TextNode(objd63e9858, d63e9733, false);

var objd63e9927 = {
  label: " html2.generate.frameset Ant parameter",
  href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateFrameset.html", 
  target:"contentwin"
};
var d63e9927 = new YAHOO.widget.TextNode(objd63e9927, d63e9733, false);

var objd63e9996 = {
  label: " html2.generate.static.toc Ant parameter",
  href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateStaticToc.html", 
  target:"contentwin"
};
var d63e9996 = new YAHOO.widget.TextNode(objd63e9996, d63e9733, false);

var objd63e11898 = {
  label: "Chapter 6.  HTML5 Plugin",
  href: "user_docs/d4p-users-guide/html5-plugin/html5-toolkit-plugin.html", 
  target:"contentwin"
};
var d63e11898 = new YAHOO.widget.TextNode(objd63e11898, d63e7351, false);

var objd63e11991 = {
  label: " Getting Started With the HTML5 Transformation",
  href: "user_docs/d4p-users-guide/html5-plugin/general/html5-getting-started.html", 
  target:"contentwin"
};
var d63e11991 = new YAHOO.widget.TextNode(objd63e11991, d63e11898, false);

var objd63e12106 = {
  label: " Requirements",
  href: "user_docs/d4p-users-guide/html5-plugin/general/requirements.html", 
  target:"contentwin"
};
var d63e12106 = new YAHOO.widget.TextNode(objd63e12106, d63e11991, false);

var objd63e12247 = {
  label: " Downloading HTML5 plugin",
  href: "user_docs/d4p-users-guide/html5-plugin/general/downloading.html", 
  target:"contentwin"
};
var d63e12247 = new YAHOO.widget.TextNode(objd63e12247, d63e11991, false);

var objd63e12389 = {
  label: " Specific installation notes for developers",
  href: "user_docs/d4p-users-guide/html5-plugin/general/install.html", 
  target:"contentwin"
};
var d63e12389 = new YAHOO.widget.TextNode(objd63e12389, d63e11991, false);

var objd63e12531 = {
  label: " Running the HTML5 Plugin",
  href: "user_docs/d4p-users-guide/html5-plugin/general/running.html", 
  target:"contentwin"
};
var d63e12531 = new YAHOO.widget.TextNode(objd63e12531, d63e11991, false);

var objd63e12673 = {
  label: " Changed Behaviours",
  href: "user_docs/d4p-users-guide/html5-plugin/general/changed_behavior.html", 
  target:"contentwin"
};
var d63e12673 = new YAHOO.widget.TextNode(objd63e12673, d63e11991, false);

var objd63e12815 = {
  label: " License",
  href: "user_docs/d4p-users-guide/html5-plugin/general/licence.html", 
  target:"contentwin"
};
var d63e12815 = new YAHOO.widget.TextNode(objd63e12815, d63e11991, false);

var objd63e12957 = {
  label: " The default theme",
  href: "user_docs/d4p-users-guide/html5-plugin/dev/html5-default-theme.html", 
  target:"contentwin"
};
var d63e12957 = new YAHOO.widget.TextNode(objd63e12957, d63e11898, false);

var objd63e13072 = {
  label: " Replacing the index.html file",
  href: "user_docs/d4p-users-guide/html5-plugin/general/setting-an-index.html", 
  target:"contentwin"
};
var d63e13072 = new YAHOO.widget.TextNode(objd63e13072, d63e12957, false);

var objd63e13214 = {
  label: " Multiple columns layout",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/muti-columns.html", 
  target:"contentwin"
};
var d63e13214 = new YAHOO.widget.TextNode(objd63e13214, d63e12957, false);

var objd63e13356 = {
  label: " CSS grid",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/css-grid.html", 
  target:"contentwin"
};
var d63e13356 = new YAHOO.widget.TextNode(objd63e13356, d63e12957, false);

var objd63e13498 = {
  label: " Image support",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/images.html", 
  target:"contentwin"
};
var d63e13498 = new YAHOO.widget.TextNode(objd63e13498, d63e12957, false);

var objd63e13640 = {
  label: " Notes",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/notes.html", 
  target:"contentwin"
};
var d63e13640 = new YAHOO.widget.TextNode(objd63e13640, d63e12957, false);

var objd63e13782 = {
  label: " UI",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/ui-intro.html", 
  target:"contentwin"
};
var d63e13782 = new YAHOO.widget.TextNode(objd63e13782, d63e12957, false);

var objd63e13924 = {
  label: " Accordion",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/accordion.html", 
  target:"contentwin"
};
var d63e13924 = new YAHOO.widget.TextNode(objd63e13924, d63e13782, false);

var objd63e14090 = {
  label: " Cycle",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/ui-images.html", 
  target:"contentwin"
};
var d63e14090 = new YAHOO.widget.TextNode(objd63e14090, d63e13782, false);

var objd63e14256 = {
  label: " Developers",
  href: "user_docs/d4p-users-guide/html5-plugin/general/developers.html", 
  target:"contentwin"
};
var d63e14256 = new YAHOO.widget.TextNode(objd63e14256, d63e11898, false);

var objd63e14373 = {
  label: " Creating a customization plugin",
  href: "user_docs/d4p-users-guide/html5-plugin/dev/customization-plugin.html", 
  target:"contentwin"
};
var d63e14373 = new YAHOO.widget.TextNode(objd63e14373, d63e14256, false);

var objd63e14515 = {
  label: " Theme Development",
  href: "user_docs/d4p-users-guide/html5-plugin/dev/theme-dev.html", 
  target:"contentwin"
};
var d63e14515 = new YAHOO.widget.TextNode(objd63e14515, d63e14256, false);

var objd63e14657 = {
  label: " The Theme cache process",
  href: "user_docs/d4p-users-guide/html5-plugin/dev/theme-general-process.html", 
  target:"contentwin"
};
var d63e14657 = new YAHOO.widget.TextNode(objd63e14657, d63e14515, false);

var objd63e14823 = {
  label: " Theme configuration file: principle",
  href: "user_docs/d4p-users-guide/html5-plugin/dev/theme-config.html", 
  target:"contentwin"
};
var d63e14823 = new YAHOO.widget.TextNode(objd63e14823, d63e14515, false);

var objd63e14989 = {
  label: " Let\'s explore the configuration file",
  href: "user_docs/d4p-users-guide/html5-plugin/dev/theme-config-file.html", 
  target:"contentwin"
};
var d63e14989 = new YAHOO.widget.TextNode(objd63e14989, d63e14515, false);

var objd63e15155 = {
  label: " How to add Internet Explorer conditional css",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/theme-add-conditional-css.html", 
  target:"contentwin"
};
var d63e15155 = new YAHOO.widget.TextNode(objd63e15155, d63e14515, false);

var objd63e15320 = {
  label: " Adding Google analytics tracking code",
  href: "user_docs/d4p-users-guide/html5-plugin/how-to/analytics.html", 
  target:"contentwin"
};
var d63e15320 = new YAHOO.widget.TextNode(objd63e15320, d63e14515, false);

var objd63e15486 = {
  label: " HTML5 Transform Reference",
  href: "user_docs/d4p-users-guide/html5-plugin/references/html5-reference.html", 
  target:"contentwin"
};
var d63e15486 = new YAHOO.widget.TextNode(objd63e15486, d63e11898, false);

var objd63e15601 = {
  label: " Directory structure",
  href: "user_docs/d4p-users-guide/html5-plugin/dev/directory-structure.html", 
  target:"contentwin"
};
var d63e15601 = new YAHOO.widget.TextNode(objd63e15601, d63e15486, false);

var objd63e15743 = {
  label: " Availaible ant properties ",
  href: "user_docs/d4p-users-guide/html5-plugin/references/ant-properties.html", 
  target:"contentwin"
};
var d63e15743 = new YAHOO.widget.TextNode(objd63e15743, d63e15486, false);

var objd63e15885 = {
  label: "Chapter 7.  Generating DITA from Documents (Word-to-DITA Transformation Framework)",
  href: "user_docs/d4p-users-guide/word2dita/word-to-dita-plugin.html", 
  target:"contentwin"
};
var d63e15885 = new YAHOO.widget.TextNode(objd63e15885, d63e7351, false);

var objd63e15929 = {
  label: "Chapter 8.  Extending the DITA for Publishers Transformations",
  href: "user_docs/d4p-users-guide/topics/extending-d4p-plugins.html", 
  target:"contentwin"
};
var d63e15929 = new YAHOO.widget.TextNode(objd63e15929, d63e7351, false);

var objd63e15973 = {
  label: "Part II.  The DITA For Publishers Markup Vocabulary",
  href: "user_docs/d4p-users-guide/vocabulary-part/vocabulary-part.html", 
  target:"contentwin"
};
var d63e15973 = new YAHOO.widget.TextNode(objd63e15973, root, false);

var objd63e16005 = {
  label: "Chapter 9.  Understanding the DITA For Publishers Markup Vocabulary",
  href: "user_docs/d4p-users-guide/vocabulary-part/d4p-vocabulary-concepts.html", 
  target:"contentwin"
};
var d63e16005 = new YAHOO.widget.TextNode(objd63e16005, d63e15973, false);

var objd63e16049 = {
  label: " DITA for Publishers Vocabulary Modules Overview",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/specialization-modules-overview.html", 
  target:"contentwin"
};
var d63e16049 = new YAHOO.widget.TextNode(objd63e16049, d63e16005, false);

var objd63e16103 = {
  label: " Publication Component Topic Types",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/d4p-topic-types.html", 
  target:"contentwin"
};
var d63e16103 = new YAHOO.widget.TextNode(objd63e16103, d63e16049, false);

var objd63e16172 = {
  label: " Publication Maps",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/pubmap-domain.html", 
  target:"contentwin"
};
var d63e16172 = new YAHOO.widget.TextNode(objd63e16172, d63e16049, false);

var objd63e16241 = {
  label: " DITA For Publishers Domains",
  href: "user_docs/d4p-users-guide/vocabulary-part/domain-modules-overview.html", 
  target:"contentwin"
};
var d63e16241 = new YAHOO.widget.TextNode(objd63e16241, d63e16049, false);

var objd63e16310 = {
  label: " Publication Map Domains",
  href: "user_docs/d4p-users-guide/vocabulary-part/map-domains-overview.html", 
  target:"contentwin"
};
var d63e16310 = new YAHOO.widget.TextNode(objd63e16310, d63e16241, false);

var objd63e16391 = {
  label: " Topic Domains",
  href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
  target:"contentwin"
};
var d63e16391 = new YAHOO.widget.TextNode(objd63e16391, d63e16241, false);

var objd63e16472 = {
  label: " Classification Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/classification-domain.html", 
  target:"contentwin"
};
var d63e16472 = new YAHOO.widget.TextNode(objd63e16472, d63e16241, false);

var objd63e16553 = {
  label: " Enumeration Domains",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/enumeration-domains.html", 
  target:"contentwin"
};
var d63e16553 = new YAHOO.widget.TextNode(objd63e16553, d63e16241, false);

var objd63e16634 = {
  label: " Formatting Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/formatting-domain.html", 
  target:"contentwin"
};
var d63e16634 = new YAHOO.widget.TextNode(objd63e16634, d63e16241, false);

var objd63e16715 = {
  label: " Publication Content Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/pubcontent-domain.html", 
  target:"contentwin"
};
var d63e16715 = new YAHOO.widget.TextNode(objd63e16715, d63e16241, false);

var objd63e16796 = {
  label: " Rendition Target Attribute Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/rendition-target-att.html", 
  target:"contentwin"
};
var d63e16796 = new YAHOO.widget.TextNode(objd63e16796, d63e16241, false);

var objd63e16880 = {
  label: " Ruby Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/ruby-domain.html", 
  target:"contentwin"
};
var d63e16880 = new YAHOO.widget.TextNode(objd63e16880, d63e16241, false);

var objd63e16964 = {
  label: " Variables Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/variables-domain.html", 
  target:"contentwin"
};
var d63e16964 = new YAHOO.widget.TextNode(objd63e16964, d63e16241, false);

var objd63e17045 = {
  label: " Verse Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/versie-domain.html", 
  target:"contentwin"
};
var d63e17045 = new YAHOO.widget.TextNode(objd63e17045, d63e16241, false);

var objd63e17127 = {
  label: " XML Domain",
  href: "user_docs/d4p-users-guide/vocabulary-part/topics/xml-domain.html", 
  target:"contentwin"
};
var d63e17127 = new YAHOO.widget.TextNode(objd63e17127, d63e16241, false);

var objd63e17206 = {
  label: "Chapter 10.  Integrating D4P Modules Into Document Type Shells",
  href: "user_docs/d4p-users-guide/vocabulary-part/integrating-modules.html", 
  target:"contentwin"
};
var d63e17206 = new YAHOO.widget.TextNode(objd63e17206, d63e15973, false);

var objd63e17250 = {
  label: " Integrating Attribute Domains",
  href: "user_docs/d4p-users-guide/vocabulary-part/integrating-attribute-domains.html", 
  target:"contentwin"
};
var d63e17250 = new YAHOO.widget.TextNode(objd63e17250, d63e17206, false);

var objd63e17309 = {
  label: "Chapter 11.  DITA For Publishers Vocabulary Reference",
  href: "user_docs/d4p-users-guide/vocabulary-part/d4p-vocabulary-reference.html", 
  target:"contentwin"
};
var d63e17309 = new YAHOO.widget.TextNode(objd63e17309, d63e15973, false);

var objd63e17353 = {
  label: "Part III.  The DITA For Publishers Word to DITA and DITA to InDesign Tools",
  href: "user_docs/d4p-users-guide/transform-frameworks-part/transform-frameworks-part.html", 
  target:"contentwin"
};
var d63e17353 = new YAHOO.widget.TextNode(objd63e17353, root, false);

var objd63e17385 = {
  label: "Chapter 12.  The Word-to-DITA Transformation Framework",
  href: "user_docs/d4p-users-guide/word2dita/word2dita-intro.html", 
  target:"contentwin"
};
var d63e17385 = new YAHOO.widget.TextNode(objd63e17385, d63e17353, false);

var objd63e17429 = {
  label: " Getting Started With The Word2DITA Transform",
  href: "user_docs/d4p-users-guide/word2dita/w2d-getting-started.html", 
  target:"contentwin"
};
var d63e17429 = new YAHOO.widget.TextNode(objd63e17429, d63e17385, false);

var objd63e17485 = {
  label: " Generating DITA from Word Using the Toolkit Plugin",
  href: "user_docs/d4p-users-guide/word2dita/word-to-dita-plugin-usage.html", 
  target:"contentwin"
};
var d63e17485 = new YAHOO.widget.TextNode(objd63e17485, d63e17385, false);

var objd63e17541 = {
  label: " Setting Up an Ant Script for Running the Word-to-DITA Transform",
  href: "user_docs/d4p-users-guide/word2dita/word-to-dita-ant-task.html", 
  target:"contentwin"
};
var d63e17541 = new YAHOO.widget.TextNode(objd63e17541, d63e17485, false);

var objd63e17610 = {
  label: " Generating DITA From Within OxygenXML",
  href: "user_docs/docx2dita_guide_and_reference/word2dita-from-oxygen.html", 
  target:"contentwin"
};
var d63e17610 = new YAHOO.widget.TextNode(objd63e17610, d63e17385, false);

var objd63e17666 = {
  label: " Style to Tag Mapping",
  href: "user_docs/docx2dita_guide_and_reference/style-to-tag-map-overview.html", 
  target:"contentwin"
};
var d63e17666 = new YAHOO.widget.TextNode(objd63e17666, d63e17385, false);

var objd63e17722 = {
  label: " Common Style-to-Tag Mapping Cases",
  href: "user_docs/d4p-users-guide/word2dita/common-mapping-cases.html", 
  target:"contentwin"
};
var d63e17722 = new YAHOO.widget.TextNode(objd63e17722, d63e17385, false);

var objd63e17778 = {
  label: " Troubleshooting the Word-to-DITA Process",
  href: "user_docs/d4p-users-guide/word2dita/troubleshooting-word2dita.html", 
  target:"contentwin"
};
var d63e17778 = new YAHOO.widget.TextNode(objd63e17778, d63e17385, false);

var objd63e17834 = {
  label: " Word-to-DITA Style-to-Tag Mapping Video Tutorial",
  href: "user_docs/d4p-users-guide/word2dita/word2dita-video-tutorial-01.html", 
  target:"contentwin"
};
var d63e17834 = new YAHOO.widget.TextNode(objd63e17834, d63e17385, false);

var objd63e17890 = {
  label: " Extending and Overriding the Word to DITA Transform",
  href: "user_docs/d4p-users-guide/word2dita/customizing-the-transform.html", 
  target:"contentwin"
};
var d63e17890 = new YAHOO.widget.TextNode(objd63e17890, d63e17385, false);

var objd63e17946 = {
  label: " Sample Custom Word-to-DITA XSLT Stylesheet",
  href: "user_docs/d4p-users-guide/word2dita/sample-customization-transform.html", 
  target:"contentwin"
};
var d63e17946 = new YAHOO.widget.TextNode(objd63e17946, d63e17890, false);

var objd63e18015 = {
  label: " Tips for Using Word With the Word-to-DITA Transform",
  href: "user_docs/d4p-users-guide/word2dita/word-usage-tips.html", 
  target:"contentwin"
};
var d63e18015 = new YAHOO.widget.TextNode(objd63e18015, d63e17385, false);

var objd63e18071 = {
  label: " Migrating the Style-to-tag Mapping",
  href: "user_docs/docx2dita_guide_and_reference/style-to-tag-map-migrate.html", 
  target:"contentwin"
};
var d63e18071 = new YAHOO.widget.TextNode(objd63e18071, d63e17385, false);

var objd63e18128 = {
  label: " Word-to-DITA XSLT Transformation Parameters",
  href: "user_docs/d4p-users-guide/word2dita/transform-parameters.html", 
  target:"contentwin"
};
var d63e18128 = new YAHOO.widget.TextNode(objd63e18128, d63e17385, false);

var objd63e18184 = {
  label: " Word-to-DITA Ant Parameters",
  href: "user_docs/d4p-users-guide/word2dita/word2dita-ant-parameters.html", 
  target:"contentwin"
};
var d63e18184 = new YAHOO.widget.TextNode(objd63e18184, d63e17385, false);

var objd63e18240 = {
  label: "Chapter 13.  The DITA-to-InDesign Transformation Framework",
  href: "user_docs/d4p-users-guide/dita2indesign/dita-to-indesign-framework-chapter.html", 
  target:"contentwin"
};
var d63e18240 = new YAHOO.widget.TextNode(objd63e18240, d63e17353, false);

var objd63e18284 = {
  label: " Overview of the InDesign and InCopy Products",
  href: "user_docs/d4p-users-guide/dita2indesign/indesign-product-overview.html", 
  target:"contentwin"
};
var d63e18284 = new YAHOO.widget.TextNode(objd63e18284, d63e18240, false);

var objd63e18340 = {
  label: " Generating InCopy Articles from DITA Topics",
  href: "user_docs/d4p-users-guide/dita2indesign/generating-incopy-articles-from-topics.html", 
  target:"contentwin"
};
var d63e18340 = new YAHOO.widget.TextNode(objd63e18340, d63e18240, false);

var objd63e18396 = {
  label: " Generating InDesign from DITA Using the Toolkit Plugin",
  href: "user_docs/d4p-users-guide/dita2indesign/dita-to-indesign-plugin-usage.html", 
  target:"contentwin"
};
var d63e18396 = new YAHOO.widget.TextNode(objd63e18396, d63e18240, false);

var objd63e18452 = {
  label: " Configuring the DITA-to-InDesign Transformation",
  href: "user_docs/d4p-users-guide/dita2indesign/generating-incopy-articles.html", 
  target:"contentwin"
};
var d63e18452 = new YAHOO.widget.TextNode(objd63e18452, d63e18240, false);

var objd63e18508 = {
  label: " Mapping XML Elements to InDesign Paragraph and Character Styles",
  href: "user_docs/d4p-users-guide/dita2indesign/mapping-paragraphs-to-indesign-styles.html", 
  target:"contentwin"
};
var d63e18508 = new YAHOO.widget.TextNode(objd63e18508, d63e18452, false);

var objd63e18577 = {
  label: " Specifying InDesign Grouped Style Names",
  href: "user_docs/d4p-users-guide/dita2indesign/grouped-style-name-syntax.html", 
  target:"contentwin"
};
var d63e18577 = new YAHOO.widget.TextNode(objd63e18577, d63e18452, false);

var objd63e18646 = {
  label: " Preparing InDesign Templates for DITA-to-InDesign Use",
  href: "user_docs/d4p-users-guide/dita2indesign/indesign-optimization.html", 
  target:"contentwin"
};
var d63e18646 = new YAHOO.widget.TextNode(objd63e18646, d63e18240, false);

var objd63e18703 = {
  label: " Colophon",
  href: "user_docs/d4p-users-guide/backmatter/colophon.html", 
  target:"contentwin"
};
var d63e18703 = new YAHOO.widget.TextNode(objd63e18703, root, false);
var d207e2670 = new YAHOO.widget.TextNode("Index", root, false);
var d207e2671 = new YAHOO.widget.TextNode("@", d207e2670, false);
var d207e2675 = new YAHOO.widget.TextNode("@font-face CSS instruction", d207e2671, false);

var objd207e2682 = {
    label: "[Using Fonts from CSS Style Sheets (@font-face)]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e2682 = new YAHOO.widget.TextNode(objd207e2682, d207e2675, false);
var d207e2686 = new YAHOO.widget.TextNode("A", d207e2670, false);
var d207e2690 = new YAHOO.widget.TextNode("ant parameters", d207e2686, false);
var d207e2699 = new YAHOO.widget.TextNode("cover.graphic.file", d207e2690, false);

var objd207e2706 = {
    label: "[cover.graphic.file Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-coverGraphicFile.html", 
    target:"contentwin"
};
var d207e2706 = new YAHOO.widget.TextNode(objd207e2706, d207e2699, false);
var d207e2710 = new YAHOO.widget.TextNode("html2.file.organization.strategy", d207e2690, false);

var objd207e2717 = {
    label: "[html2.file.organization.strategy Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-fileOrganizationStrategy.html", 
    target:"contentwin"
};
var d207e2717 = new YAHOO.widget.TextNode(objd207e2717, d207e2710, false);
var d207e2721 = new YAHOO.widget.TextNode("html2.generate.dynamic.toc", d207e2690, false);

var objd207e2728 = {
    label: "[html2.generate.dynamic.toc Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateDynamicToc.html", 
    target:"contentwin"
};
var d207e2728 = new YAHOO.widget.TextNode(objd207e2728, d207e2721, false);
var d207e2732 = new YAHOO.widget.TextNode("html2.generate.frameset", d207e2690, false);

var objd207e2739 = {
    label: "[html2.generate.frameset Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateFrameset.html", 
    target:"contentwin"
};
var d207e2739 = new YAHOO.widget.TextNode(objd207e2739, d207e2732, false);
var d207e2743 = new YAHOO.widget.TextNode("html2.generate.static.toc", d207e2690, false);

var objd207e2750 = {
    label: "[html2.generate.static.toc Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateStaticToc.html", 
    target:"contentwin"
};
var d207e2750 = new YAHOO.widget.TextNode(objd207e2750, d207e2743, false);
var d207e2754 = new YAHOO.widget.TextNode("kindlegen.executable", d207e2690, false);

var objd207e2761 = {
    label: "[kindlegen.executable Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-kindleGenExecutable.html", 
    target:"contentwin"
};
var d207e2761 = new YAHOO.widget.TextNode(objd207e2761, d207e2754, false);
var d207e2765 = new YAHOO.widget.TextNode("B", d207e2670, false);
var d207e2769 = new YAHOO.widget.TextNode("built-in CSS", d207e2765, false);

var objd207e2776 = {
    label: "[Using Custom CSS Style Sheets]",
    href: "user_docs/d4p-users-guide/epub-plugin/using-custom-css.html", 
    target:"contentwin"
};
var d207e2776 = new YAHOO.widget.TextNode(objd207e2776, d207e2769, false);
var d207e2780 = new YAHOO.widget.TextNode("C", d207e2670, false);
var d207e2784 = new YAHOO.widget.TextNode("classification domain", d207e2780, false);

var objd207e2791 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e2791 = new YAHOO.widget.TextNode(objd207e2791, d207e2784, false);
var d207e2795 = new YAHOO.widget.TextNode("collected data", d207e2780, false);

var objd207e2803 = {
    label: "[Numbering Things: Collected Data and Enumeration]",
    href: "user_docs/d4p-users-guide/map-driven-processing/enumeration.html", 
    target:"contentwin"
};
var d207e2803 = new YAHOO.widget.TextNode(objd207e2803, d207e2795, false);
var d207e2806 = new YAHOO.widget.TextNode("cover", d207e2780, false);
var d207e2815 = new YAHOO.widget.TextNode("generating", d207e2806, false);

var objd207e2822 = {
    label: "[cover.graphic.file Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-coverGraphicFile.html", 
    target:"contentwin"
};
var d207e2822 = new YAHOO.widget.TextNode(objd207e2822, d207e2815, false);
var d207e2826 = new YAHOO.widget.TextNode("graphic for", d207e2806, false);

var objd207e2833 = {
    label: "[Creating Cover Graphics and Covers]",
    href: "user_docs/d4p-users-guide/epub-plugin/creating-cover-graphics.html", 
    target:"contentwin"
};
var d207e2833 = new YAHOO.widget.TextNode(objd207e2833, d207e2826, false);
var d207e2837 = new YAHOO.widget.TextNode("cover.graphic.file ant parameter", d207e2780, false);

var objd207e2844 = {
    label: "[cover.graphic.file Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-coverGraphicFile.html", 
    target:"contentwin"
};
var d207e2844 = new YAHOO.widget.TextNode(objd207e2844, d207e2837, false);
var d207e2848 = new YAHOO.widget.TextNode("css", d207e2780, false);
var d207e2857 = new YAHOO.widget.TextNode("@font-face instructions", d207e2848, false);

var objd207e2864 = {
    label: "[Using Fonts from CSS Style Sheets (@font-face)]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e2864 = new YAHOO.widget.TextNode(objd207e2864, d207e2857, false);
var d207e2868 = new YAHOO.widget.TextNode("custom", d207e2848, false);

var objd207e2875 = {
    label: "[Using Custom CSS Style Sheets]",
    href: "user_docs/d4p-users-guide/epub-plugin/using-custom-css.html", 
    target:"contentwin"
};
var d207e2875 = new YAHOO.widget.TextNode(objd207e2875, d207e2868, false);
var d207e2879 = new YAHOO.widget.TextNode("D", d207e2670, false);
var d207e2883 = new YAHOO.widget.TextNode("data collection", d207e2879, false);
var d207e2892 = new YAHOO.widget.TextNode("overview", d207e2883, false);

var objd207e2899 = {
    label: "[Data Collection Processing Phase]",
    href: "user_docs/d4p-users-guide/map-driven-processing/data-collection.html", 
    target:"contentwin"
};
var d207e2899 = new YAHOO.widget.TextNode(objd207e2899, d207e2892, false);
var d207e2903 = new YAHOO.widget.TextNode("DITA-to-InDesign", d207e2879, false);

var objd207e2910 = {
    label: "[Generating InDesign from DITA Using the Toolkit Plugin]",
    href: "user_docs/d4p-users-guide/dita2indesign/dita-to-indesign-plugin-usage.html", 
    target:"contentwin"
};
var d207e2910 = new YAHOO.widget.TextNode(objd207e2910, d207e2903, false);
var d207e2914 = new YAHOO.widget.TextNode("domain modules", d207e2879, false);

var objd207e2921 = {
    label: "[DITA For Publishers Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/domain-modules-overview.html", 
    target:"contentwin"
};
var d207e2921 = new YAHOO.widget.TextNode(objd207e2921, d207e2914, false);
var d207e2925 = new YAHOO.widget.TextNode("domains", d207e2879, false);
var d207e2944 = new YAHOO.widget.TextNode("classification", d207e2925, false);

var objd207e2951 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e2951 = new YAHOO.widget.TextNode(objd207e2951, d207e2944, false);
var d207e2955 = new YAHOO.widget.TextNode("enumeration", d207e2925, false);

var objd207e2962 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e2962 = new YAHOO.widget.TextNode(objd207e2962, d207e2955, false);
var d207e2966 = new YAHOO.widget.TextNode("formatting", d207e2925, false);

var objd207e2973 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e2973 = new YAHOO.widget.TextNode(objd207e2973, d207e2966, false);
var d207e2977 = new YAHOO.widget.TextNode("publication content", d207e2925, false);

var objd207e2984 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e2984 = new YAHOO.widget.TextNode(objd207e2984, d207e2977, false);
var d207e2988 = new YAHOO.widget.TextNode("topic", d207e2925, false);

var objd207e2995 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e2995 = new YAHOO.widget.TextNode(objd207e2995, d207e2988, false);
var d207e2999 = new YAHOO.widget.TextNode("verse", d207e2925, false);

var objd207e3006 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e3006 = new YAHOO.widget.TextNode(objd207e3006, d207e2999, false);
var d207e3010 = new YAHOO.widget.TextNode("E", d207e2670, false);
var d207e3014 = new YAHOO.widget.TextNode("elements in context", d207e3010, false);
var d207e3023 = new YAHOO.widget.TextNode("mapping to InDesign styles", d207e3014, false);

var objd207e3030 = {
    label: "[Mapping XML Elements to InDesign Paragraph and Character Styles]",
    href: "user_docs/d4p-users-guide/dita2indesign/mapping-paragraphs-to-indesign-styles.html", 
    target:"contentwin"
};
var d207e3030 = new YAHOO.widget.TextNode(objd207e3030, d207e3023, false);
var d207e3034 = new YAHOO.widget.TextNode("embedding", d207e3010, false);
var d207e3043 = new YAHOO.widget.TextNode("fonts", d207e3034, false);

var objd207e3050 = {
    label: "[Embedding Fonts in Your EPUB]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3050 = new YAHOO.widget.TextNode(objd207e3050, d207e3043, false);
var d207e3054 = new YAHOO.widget.TextNode("enumeration", d207e3010, false);
var d207e3063 = new YAHOO.widget.TextNode("customizing for HTML output", d207e3054, false);

var objd207e3070 = {
    label: "[Extending and Customizing Enumeration Processing (Numbering)]",
    href: "user_docs/d4p-users-guide/html2-plugin/customizing-enumeration.html", 
    target:"contentwin"
};
var d207e3070 = new YAHOO.widget.TextNode(objd207e3070, d207e3063, false);
var d207e3074 = new YAHOO.widget.TextNode("data collection\n        for", d207e3054, false);

var objd207e3081 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e3081 = new YAHOO.widget.TextNode(objd207e3081, d207e3074, false);
var d207e3085 = new YAHOO.widget.TextNode("enumeration domain", d207e3010, false);

var objd207e3092 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e3092 = new YAHOO.widget.TextNode(objd207e3092, d207e3085, false);
var d207e3096 = new YAHOO.widget.TextNode("EPUB", d207e3010, false);
var d207e3107 = new YAHOO.widget.TextNode("generating", d207e3096, false);
var d207e3116 = new YAHOO.widget.TextNode("with OxygenXML", d207e3107, false);

var objd207e3123 = {
    label: "[Generating EPUBs From OxygenXML]",
    href: "user_docs/d4p-users-guide/epub-plugin/generating-epubs-from-oxygen.html", 
    target:"contentwin"
};
var d207e3123 = new YAHOO.widget.TextNode(objd207e3123, d207e3116, false);
var d207e3127 = new YAHOO.widget.TextNode("extending", d207e3010, false);
var d207e3136 = new YAHOO.widget.TextNode("plugins", d207e3127, false);

var objd207e3143 = {
    label: "[Extending the DITA for Publishers Transformations]",
    href: "user_docs/d4p-users-guide/topics/extending-d4p-plugins.html", 
    target:"contentwin"
};
var d207e3143 = new YAHOO.widget.TextNode(objd207e3143, d207e3136, false);
var d207e3147 = new YAHOO.widget.TextNode("extension points", d207e3010, false);
var d207e3156 = new YAHOO.widget.TextNode("data\n      collection", d207e3147, false);

var objd207e3163 = {
    label: "[Data Collection Processing Phase]",
    href: "user_docs/d4p-users-guide/map-driven-processing/data-collection.html", 
    target:"contentwin"
};
var d207e3163 = new YAHOO.widget.TextNode(objd207e3163, d207e3156, false);
var d207e3167 = new YAHOO.widget.TextNode("F", d207e2670, false);
var d207e3171 = new YAHOO.widget.TextNode("font", d207e3167, false);
var d207e3180 = new YAHOO.widget.TextNode("embedding in EPUB", d207e3171, false);

var objd207e3187 = {
    label: "[Embedding Fonts in Your EPUB]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3187 = new YAHOO.widget.TextNode(objd207e3187, d207e3180, false);
var d207e3191 = new YAHOO.widget.TextNode("manifest (for embedding)", d207e3171, false);

var objd207e3198 = {
    label: "[Embedding Fonts in Your EPUB]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3198 = new YAHOO.widget.TextNode(objd207e3198, d207e3191, false);

var objd207e3201 = {
    label: "[The Font Manifest File]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3201 = new YAHOO.widget.TextNode(objd207e3201, d207e3191, false);
var d207e3205 = new YAHOO.widget.TextNode("using from CSS", d207e3171, false);

var objd207e3212 = {
    label: "[Using Fonts from CSS Style Sheets (@font-face)]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3212 = new YAHOO.widget.TextNode(objd207e3212, d207e3205, false);
var d207e3216 = new YAHOO.widget.TextNode("font embedding", d207e3167, false);

var objd207e3223 = {
    label: "[Embedding Fonts in Your EPUB]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3223 = new YAHOO.widget.TextNode(objd207e3223, d207e3216, false);
var d207e3227 = new YAHOO.widget.TextNode("formatting domain", d207e3167, false);

var objd207e3234 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e3234 = new YAHOO.widget.TextNode(objd207e3234, d207e3227, false);
var d207e3238 = new YAHOO.widget.TextNode("frameset", d207e3167, false);
var d207e3247 = new YAHOO.widget.TextNode("generating", d207e3238, false);

var objd207e3254 = {
    label: "[html2.generate.frameset Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateFrameset.html", 
    target:"contentwin"
};
var d207e3254 = new YAHOO.widget.TextNode(objd207e3254, d207e3247, false);
var d207e3258 = new YAHOO.widget.TextNode("G", d207e2670, false);
var d207e3262 = new YAHOO.widget.TextNode("glossary entries", d207e3258, false);
var d207e3271 = new YAHOO.widget.TextNode("grouping and\n        sorting", d207e3262, false);

var objd207e3278 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e3278 = new YAHOO.widget.TextNode(objd207e3278, d207e3271, false);
var d207e3282 = new YAHOO.widget.TextNode("graphic map", d207e3258, false);
var d207e3291 = new YAHOO.widget.TextNode("extending", d207e3282, false);

var objd207e3298 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e3298 = new YAHOO.widget.TextNode(objd207e3298, d207e3291, false);
var d207e3302 = new YAHOO.widget.TextNode("generating", d207e3282, false);

var objd207e3309 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e3309 = new YAHOO.widget.TextNode(objd207e3309, d207e3302, false);
var d207e3313 = new YAHOO.widget.TextNode("graphics", d207e3258, false);
var d207e3322 = new YAHOO.widget.TextNode("cover", d207e3313, false);

var objd207e3329 = {
    label: "[Creating Cover Graphics and Covers]",
    href: "user_docs/d4p-users-guide/epub-plugin/creating-cover-graphics.html", 
    target:"contentwin"
};
var d207e3329 = new YAHOO.widget.TextNode(objd207e3329, d207e3322, false);
var d207e3333 = new YAHOO.widget.TextNode("including in output", d207e3313, false);

var objd207e3340 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e3340 = new YAHOO.widget.TextNode(objd207e3340, d207e3333, false);
var d207e3344 = new YAHOO.widget.TextNode("grouped InDesign styles", d207e3258, false);

var objd207e3351 = {
    label: "[Specifying InDesign Grouped Style Names]",
    href: "user_docs/d4p-users-guide/dita2indesign/grouped-style-name-syntax.html", 
    target:"contentwin"
};
var d207e3351 = new YAHOO.widget.TextNode(objd207e3351, d207e3344, false);
var d207e3355 = new YAHOO.widget.TextNode("H", d207e2670, false);
var d207e3359 = new YAHOO.widget.TextNode("HTML", d207e3355, false);
var d207e3368 = new YAHOO.widget.TextNode("generating", d207e3359, false);

var objd207e3375 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e3375 = new YAHOO.widget.TextNode(objd207e3375, d207e3368, false);

var objd207e3378 = {
    label: "[HTML2 Plugin]",
    href: "user_docs/d4p-users-guide/html2-plugin/html2-toolkit-plugin.html", 
    target:"contentwin"
};
var d207e3378 = new YAHOO.widget.TextNode(objd207e3378, d207e3368, false);

var objd207e3381 = {
    label: "[Replacing the index.html file]",
    href: "user_docs/d4p-users-guide/html5-plugin/general/setting-an-index.html", 
    target:"contentwin"
};
var d207e3381 = new YAHOO.widget.TextNode(objd207e3381, d207e3368, false);
var d207e3385 = new YAHOO.widget.TextNode("HTML5", d207e3359, false);

var objd207e3392 = {
    label: "[HTML5 Plugin]",
    href: "user_docs/d4p-users-guide/html5-plugin/html5-toolkit-plugin.html", 
    target:"contentwin"
};
var d207e3392 = new YAHOO.widget.TextNode(objd207e3392, d207e3385, false);

var objd207e3395 = {
    label: "[Replacing the index.html file]",
    href: "user_docs/d4p-users-guide/html5-plugin/general/setting-an-index.html", 
    target:"contentwin"
};
var d207e3395 = new YAHOO.widget.TextNode(objd207e3395, d207e3385, false);
var d207e3399 = new YAHOO.widget.TextNode("html2.file.organization.strategy ant parameter", d207e3355, false);

var objd207e3406 = {
    label: "[html2.file.organization.strategy Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-fileOrganizationStrategy.html", 
    target:"contentwin"
};
var d207e3406 = new YAHOO.widget.TextNode(objd207e3406, d207e3399, false);
var d207e3410 = new YAHOO.widget.TextNode("html2.generate.dynamic.toc ant parameter", d207e3355, false);

var objd207e3417 = {
    label: "[html2.generate.dynamic.toc Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateDynamicToc.html", 
    target:"contentwin"
};
var d207e3417 = new YAHOO.widget.TextNode(objd207e3417, d207e3410, false);
var d207e3421 = new YAHOO.widget.TextNode("html2.generate.frameset ant parameter", d207e3355, false);

var objd207e3428 = {
    label: "[html2.generate.frameset Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateFrameset.html", 
    target:"contentwin"
};
var d207e3428 = new YAHOO.widget.TextNode(objd207e3428, d207e3421, false);
var d207e3432 = new YAHOO.widget.TextNode("html2.generate.static.toc ant parameter", d207e3355, false);

var objd207e3439 = {
    label: "[html2.generate.static.toc Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateStaticToc.html", 
    target:"contentwin"
};
var d207e3439 = new YAHOO.widget.TextNode(objd207e3439, d207e3432, false);
var d207e3443 = new YAHOO.widget.TextNode("HTML2 Toolkit plugin", d207e3355, false);

var objd207e3450 = {
    label: "[HTML2 Plugin]",
    href: "user_docs/d4p-users-guide/html2-plugin/html2-toolkit-plugin.html", 
    target:"contentwin"
};
var d207e3450 = new YAHOO.widget.TextNode(objd207e3450, d207e3443, false);
var d207e3454 = new YAHOO.widget.TextNode("HTML5 Toolkit plugin", d207e3355, false);

var objd207e3461 = {
    label: "[HTML5 Plugin]",
    href: "user_docs/d4p-users-guide/html5-plugin/html5-toolkit-plugin.html", 
    target:"contentwin"
};
var d207e3461 = new YAHOO.widget.TextNode(objd207e3461, d207e3454, false);

var objd207e3464 = {
    label: "[Replacing the index.html file]",
    href: "user_docs/d4p-users-guide/html5-plugin/general/setting-an-index.html", 
    target:"contentwin"
};
var d207e3464 = new YAHOO.widget.TextNode(objd207e3464, d207e3454, false);
var d207e3468 = new YAHOO.widget.TextNode("I", d207e2670, false);
var d207e3472 = new YAHOO.widget.TextNode("InCopy", d207e3468, false);
var d207e3479 = new YAHOO.widget.TextNode("generating articles from maps and topics", d207e3472, false);

var objd207e3486 = {
    label: "[Configuring the DITA-to-InDesign Transformation]",
    href: "user_docs/d4p-users-guide/dita2indesign/generating-incopy-articles.html", 
    target:"contentwin"
};
var d207e3486 = new YAHOO.widget.TextNode(objd207e3486, d207e3479, false);
var d207e3490 = new YAHOO.widget.TextNode("InDesign", d207e3468, false);
var d207e3501 = new YAHOO.widget.TextNode("generating from DITA", d207e3490, false);

var objd207e3508 = {
    label: "[The DITA-to-InDesign Transformation Framework]",
    href: "user_docs/d4p-users-guide/dita2indesign/dita-to-indesign-framework-chapter.html", 
    target:"contentwin"
};
var d207e3508 = new YAHOO.widget.TextNode(objd207e3508, d207e3501, false);
var d207e3512 = new YAHOO.widget.TextNode("group styles", d207e3490, false);

var objd207e3519 = {
    label: "[Specifying InDesign Grouped Style Names]",
    href: "user_docs/d4p-users-guide/dita2indesign/grouped-style-name-syntax.html", 
    target:"contentwin"
};
var d207e3519 = new YAHOO.widget.TextNode(objd207e3519, d207e3512, false);
var d207e3523 = new YAHOO.widget.TextNode("optimizing for automation", d207e3490, false);

var objd207e3530 = {
    label: "[Preparing InDesign Templates for DITA-to-InDesign Use]",
    href: "user_docs/d4p-users-guide/dita2indesign/indesign-optimization.html", 
    target:"contentwin"
};
var d207e3530 = new YAHOO.widget.TextNode(objd207e3530, d207e3523, false);
var d207e3534 = new YAHOO.widget.TextNode("styles, grouped", d207e3490, false);

var objd207e3541 = {
    label: "[Specifying InDesign Grouped Style Names]",
    href: "user_docs/d4p-users-guide/dita2indesign/grouped-style-name-syntax.html", 
    target:"contentwin"
};
var d207e3541 = new YAHOO.widget.TextNode(objd207e3541, d207e3534, false);
var d207e3545 = new YAHOO.widget.TextNode("transformation framework", d207e3490, false);

var objd207e3552 = {
    label: "[The DITA-to-InDesign Transformation Framework]",
    href: "user_docs/d4p-users-guide/dita2indesign/dita-to-indesign-framework-chapter.html", 
    target:"contentwin"
};
var d207e3552 = new YAHOO.widget.TextNode(objd207e3552, d207e3545, false);
var d207e3556 = new YAHOO.widget.TextNode("InDesign styles", d207e3468, false);
var d207e3565 = new YAHOO.widget.TextNode("mapping elements in context to", d207e3556, false);

var objd207e3572 = {
    label: "[Mapping XML Elements to InDesign Paragraph and Character Styles]",
    href: "user_docs/d4p-users-guide/dita2indesign/mapping-paragraphs-to-indesign-styles.html", 
    target:"contentwin"
};
var d207e3572 = new YAHOO.widget.TextNode(objd207e3572, d207e3565, false);
var d207e3576 = new YAHOO.widget.TextNode("index", d207e3468, false);
var d207e3585 = new YAHOO.widget.TextNode("generation of", d207e3576, false);

var objd207e3592 = {
    label: "[Index Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/index-generation.html", 
    target:"contentwin"
};
var d207e3592 = new YAHOO.widget.TextNode(objd207e3592, d207e3585, false);
var d207e3596 = new YAHOO.widget.TextNode("index.html, generating", d207e3468, false);

var objd207e3603 = {
    label: "[HTML5 Plugin]",
    href: "user_docs/d4p-users-guide/html5-plugin/html5-toolkit-plugin.html", 
    target:"contentwin"
};
var d207e3603 = new YAHOO.widget.TextNode(objd207e3603, d207e3596, false);

var objd207e3606 = {
    label: "[Replacing the index.html file]",
    href: "user_docs/d4p-users-guide/html5-plugin/general/setting-an-index.html", 
    target:"contentwin"
};
var d207e3606 = new YAHOO.widget.TextNode(objd207e3606, d207e3596, false);
var d207e3610 = new YAHOO.widget.TextNode("index generation", d207e3468, false);

var objd207e3617 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e3617 = new YAHOO.widget.TextNode(objd207e3617, d207e3610, false);
var d207e3621 = new YAHOO.widget.TextNode("installing toolkit plugins", d207e3468, false);

var objd207e3628 = {
    label: "[Installing the Toolkit Plugins]",
    href: "user_docs/d4p-users-guide/tasks/plugin-installation.html", 
    target:"contentwin"
};
var d207e3628 = new YAHOO.widget.TextNode(objd207e3628, d207e3621, false);
var d207e3632 = new YAHOO.widget.TextNode("K", d207e2670, false);
var d207e3636 = new YAHOO.widget.TextNode("kindle book", d207e3632, false);
var d207e3645 = new YAHOO.widget.TextNode("generating", d207e3636, false);

var objd207e3652 = {
    label: "[kindlegen.executable Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-kindleGenExecutable.html", 
    target:"contentwin"
};
var d207e3652 = new YAHOO.widget.TextNode(objd207e3652, d207e3645, false);
var d207e3656 = new YAHOO.widget.TextNode("Kindle book", d207e3632, false);
var d207e3667 = new YAHOO.widget.TextNode("generating", d207e3656, false);
var d207e3676 = new YAHOO.widget.TextNode("with OxygenXML", d207e3667, false);

var objd207e3683 = {
    label: "[Generating Kindle Books From OxygenXML]",
    href: "user_docs/d4p-users-guide/epub-plugin/generating-kindle-books-from-oxygen.html", 
    target:"contentwin"
};
var d207e3683 = new YAHOO.widget.TextNode(objd207e3683, d207e3676, false);
var d207e3687 = new YAHOO.widget.TextNode("kindlegen", d207e3632, false);

var objd207e3694 = {
    label: "[Setting Up The kindlegen Command-Line Utility]",
    href: "user_docs/d4p-users-guide/epub-plugin/setting-up-kindlegen.html", 
    target:"contentwin"
};
var d207e3694 = new YAHOO.widget.TextNode(objd207e3694, d207e3687, false);
var d207e3698 = new YAHOO.widget.TextNode("kindlegen.executable ant parameter", d207e3632, false);

var objd207e3705 = {
    label: "[kindlegen.executable Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-kindleGenExecutable.html", 
    target:"contentwin"
};
var d207e3705 = new YAHOO.widget.TextNode(objd207e3705, d207e3698, false);
var d207e3710 = new YAHOO.widget.TextNode("M", d207e2670, false);
var d207e3714 = new YAHOO.widget.TextNode("manifest", d207e3710, false);

var objd207e3721 = {
    label: "[Embedding Fonts in Your EPUB]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3721 = new YAHOO.widget.TextNode(objd207e3721, d207e3714, false);

var objd207e3724 = {
    label: "[The Font Manifest File]",
    href: "user_docs/d4p-users-guide/epub-plugin/embedding-fonts.html", 
    target:"contentwin"
};
var d207e3724 = new YAHOO.widget.TextNode(objd207e3724, d207e3714, false);
var d207e3728 = new YAHOO.widget.TextNode("map-driven processing", d207e3710, false);
var d207e3737 = new YAHOO.widget.TextNode("data\n          collection", d207e3728, false);

var objd207e3744 = {
    label: "[Data Collection Processing Phase]",
    href: "user_docs/d4p-users-guide/map-driven-processing/data-collection.html", 
    target:"contentwin"
};
var d207e3744 = new YAHOO.widget.TextNode(objd207e3744, d207e3737, false);
var d207e3748 = new YAHOO.widget.TextNode("generating HTML", d207e3728, false);

var objd207e3755 = {
    label: "[HTML2 Plugin]",
    href: "user_docs/d4p-users-guide/html2-plugin/html2-toolkit-plugin.html", 
    target:"contentwin"
};
var d207e3755 = new YAHOO.widget.TextNode(objd207e3755, d207e3748, false);

var objd207e3758 = {
    label: "[HTML5 Plugin]",
    href: "user_docs/d4p-users-guide/html5-plugin/html5-toolkit-plugin.html", 
    target:"contentwin"
};
var d207e3758 = new YAHOO.widget.TextNode(objd207e3758, d207e3748, false);

var objd207e3761 = {
    label: "[Replacing the index.html file]",
    href: "user_docs/d4p-users-guide/html5-plugin/general/setting-an-index.html", 
    target:"contentwin"
};
var d207e3761 = new YAHOO.widget.TextNode(objd207e3761, d207e3748, false);
var d207e3765 = new YAHOO.widget.TextNode("using", d207e3728, false);

var objd207e3772 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e3772 = new YAHOO.widget.TextNode(objd207e3772, d207e3765, false);
var d207e3776 = new YAHOO.widget.TextNode("maps", d207e3710, false);
var d207e3785 = new YAHOO.widget.TextNode("processing topics in terms\n          of", d207e3776, false);

var objd207e3792 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e3792 = new YAHOO.widget.TextNode(objd207e3792, d207e3785, false);
var d207e3796 = new YAHOO.widget.TextNode("metadata", d207e3710, false);
var d207e3807 = new YAHOO.widget.TextNode("creating", d207e3796, false);

var objd207e3814 = {
    label: "[Creating Arbitrary EPUB OPF Metadata]",
    href: "user_docs/d4p-users-guide/epub-plugin/creating-opf-metadata.html", 
    target:"contentwin"
};
var d207e3814 = new YAHOO.widget.TextNode(objd207e3814, d207e3807, false);
var d207e3818 = new YAHOO.widget.TextNode("OPF", d207e3796, false);

var objd207e3825 = {
    label: "[Creating Arbitrary EPUB OPF Metadata]",
    href: "user_docs/d4p-users-guide/epub-plugin/creating-opf-metadata.html", 
    target:"contentwin"
};
var d207e3825 = new YAHOO.widget.TextNode(objd207e3825, d207e3818, false);
var d207e3829 = new YAHOO.widget.TextNode("MS Word", d207e3710, false);
var d207e3838 = new YAHOO.widget.TextNode("to-DITA transformation framework", d207e3829, false);

var objd207e3845 = {
    label: "[The DITA For Publishers Word to DITA and DITA to InDesign Tools]",
    href: "user_docs/d4p-users-guide/transform-frameworks-part/transform-frameworks-part.html", 
    target:"contentwin"
};
var d207e3845 = new YAHOO.widget.TextNode(objd207e3845, d207e3838, false);
var d207e3849 = new YAHOO.widget.TextNode("N", d207e2670, false);
var d207e3853 = new YAHOO.widget.TextNode("numbering", d207e3849, false);
var d207e3862 = new YAHOO.widget.TextNode("of things with\n        titles", d207e3853, false);

var objd207e3869 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e3869 = new YAHOO.widget.TextNode(objd207e3869, d207e3862, false);
var d207e3873 = new YAHOO.widget.TextNode("O", d207e2670, false);
var d207e3877 = new YAHOO.widget.TextNode("Open Toolkit plugins", d207e3873, false);
var d207e3886 = new YAHOO.widget.TextNode("Word-to-DITA transform", d207e3877, false);

var objd207e3893 = {
    label: "[Generating DITA from Documents (Word-to-DITA Transformation Framework)]",
    href: "user_docs/d4p-users-guide/word2dita/word-to-dita-plugin.html", 
    target:"contentwin"
};
var d207e3893 = new YAHOO.widget.TextNode(objd207e3893, d207e3886, false);
var d207e3897 = new YAHOO.widget.TextNode("OPF metadata", d207e3873, false);
var d207e3906 = new YAHOO.widget.TextNode("creating", d207e3897, false);

var objd207e3913 = {
    label: "[Creating Arbitrary EPUB OPF Metadata]",
    href: "user_docs/d4p-users-guide/epub-plugin/creating-opf-metadata.html", 
    target:"contentwin"
};
var d207e3913 = new YAHOO.widget.TextNode(objd207e3913, d207e3906, false);
var d207e3917 = new YAHOO.widget.TextNode("output file organization strategy", d207e3873, false);
var d207e3926 = new YAHOO.widget.TextNode("generating", d207e3917, false);

var objd207e3933 = {
    label: "[html2.file.organization.strategy Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-fileOrganizationStrategy.html", 
    target:"contentwin"
};
var d207e3933 = new YAHOO.widget.TextNode(objd207e3933, d207e3926, false);
var d207e3937 = new YAHOO.widget.TextNode("overriding base processing", d207e3873, false);

var objd207e3944 = {
    label: "[Implementing Overrides for Common Processing]",
    href: "user_docs/d4p-users-guide/epub-plugin/overriding-base-processing.html", 
    target:"contentwin"
};
var d207e3944 = new YAHOO.widget.TextNode(objd207e3944, d207e3937, false);
var d207e3948 = new YAHOO.widget.TextNode("OxygenXML", d207e3873, false);
var d207e3957 = new YAHOO.widget.TextNode("generating EPUBs with", d207e3948, false);

var objd207e3964 = {
    label: "[Generating EPUBs From OxygenXML]",
    href: "user_docs/d4p-users-guide/epub-plugin/generating-epubs-from-oxygen.html", 
    target:"contentwin"
};
var d207e3964 = new YAHOO.widget.TextNode(objd207e3964, d207e3957, false);
var d207e3968 = new YAHOO.widget.TextNode("generating Kindle books with", d207e3948, false);

var objd207e3975 = {
    label: "[Generating Kindle Books From OxygenXML]",
    href: "user_docs/d4p-users-guide/epub-plugin/generating-kindle-books-from-oxygen.html", 
    target:"contentwin"
};
var d207e3975 = new YAHOO.widget.TextNode(objd207e3975, d207e3968, false);
var d207e3979 = new YAHOO.widget.TextNode("running Word-to-DITA transform with", d207e3948, false);

var objd207e3986 = {
    label: "[Generating DITA From Within OxygenXML]",
    href: "user_docs/docx2dita_guide_and_reference/word2dita-from-oxygen.html", 
    target:"contentwin"
};
var d207e3986 = new YAHOO.widget.TextNode(objd207e3986, d207e3979, false);
var d207e3990 = new YAHOO.widget.TextNode("P", d207e2670, false);
var d207e3994 = new YAHOO.widget.TextNode("parameters", d207e3990, false);
var d207e4005 = new YAHOO.widget.TextNode("ant", d207e3994, false);
var d207e4014 = new YAHOO.widget.TextNode("cover.graphic.file", d207e4005, false);

var objd207e4021 = {
    label: "[cover.graphic.file Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-coverGraphicFile.html", 
    target:"contentwin"
};
var d207e4021 = new YAHOO.widget.TextNode(objd207e4021, d207e4014, false);
var d207e4025 = new YAHOO.widget.TextNode("html2.file.organization.strategy", d207e4005, false);

var objd207e4032 = {
    label: "[html2.file.organization.strategy Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-fileOrganizationStrategy.html", 
    target:"contentwin"
};
var d207e4032 = new YAHOO.widget.TextNode(objd207e4032, d207e4025, false);
var d207e4036 = new YAHOO.widget.TextNode("html2.generate.dynamic.toc", d207e4005, false);

var objd207e4043 = {
    label: "[html2.generate.dynamic.toc Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateDynamicToc.html", 
    target:"contentwin"
};
var d207e4043 = new YAHOO.widget.TextNode(objd207e4043, d207e4036, false);
var d207e4047 = new YAHOO.widget.TextNode("html2.generate.frameset", d207e4005, false);

var objd207e4054 = {
    label: "[html2.generate.frameset Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateFrameset.html", 
    target:"contentwin"
};
var d207e4054 = new YAHOO.widget.TextNode(objd207e4054, d207e4047, false);
var d207e4058 = new YAHOO.widget.TextNode("html2.generate.static.toc", d207e4005, false);

var objd207e4065 = {
    label: "[html2.generate.static.toc Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateStaticToc.html", 
    target:"contentwin"
};
var d207e4065 = new YAHOO.widget.TextNode(objd207e4065, d207e4058, false);
var d207e4069 = new YAHOO.widget.TextNode("kindlegen.executable", d207e4005, false);

var objd207e4076 = {
    label: "[kindlegen.executable Ant parameter]",
    href: "user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-kindleGenExecutable.html", 
    target:"contentwin"
};
var d207e4076 = new YAHOO.widget.TextNode(objd207e4076, d207e4069, false);
var d207e4080 = new YAHOO.widget.TextNode("plugins", d207e3990, false);
var d207e4089 = new YAHOO.widget.TextNode("extending", d207e4080, false);

var objd207e4096 = {
    label: "[Extending the DITA for Publishers Transformations]",
    href: "user_docs/d4p-users-guide/topics/extending-d4p-plugins.html", 
    target:"contentwin"
};
var d207e4096 = new YAHOO.widget.TextNode(objd207e4096, d207e4089, false);
var d207e4100 = new YAHOO.widget.TextNode("publication content domain", d207e3990, false);

var objd207e4107 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e4107 = new YAHOO.widget.TextNode(objd207e4107, d207e4100, false);
var d207e4111 = new YAHOO.widget.TextNode("R", d207e2670, false);
var d207e4115 = new YAHOO.widget.TextNode("release notes", d207e4111, false);
var d207e4122 = new YAHOO.widget.TextNode("Version 0.9.10", d207e4115, false);

var objd207e4129 = {
    label: "[Release Notes: Version 0.9.10]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.10.html", 
    target:"contentwin"
};
var d207e4129 = new YAHOO.widget.TextNode(objd207e4129, d207e4122, false);
var d207e4133 = new YAHOO.widget.TextNode("Version 0.9.11", d207e4115, false);

var objd207e4140 = {
    label: "[Release Notes: Version 0.9.11]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.11.html", 
    target:"contentwin"
};
var d207e4140 = new YAHOO.widget.TextNode(objd207e4140, d207e4133, false);
var d207e4144 = new YAHOO.widget.TextNode("Version 0.9.12", d207e4115, false);

var objd207e4151 = {
    label: "[Release Notes: Version 0.9.12]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.12.html", 
    target:"contentwin"
};
var d207e4151 = new YAHOO.widget.TextNode(objd207e4151, d207e4144, false);
var d207e4155 = new YAHOO.widget.TextNode("Version 0.9.13", d207e4115, false);

var objd207e4162 = {
    label: "[Release Notes: Version 0.9.13]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.13.html", 
    target:"contentwin"
};
var d207e4162 = new YAHOO.widget.TextNode(objd207e4162, d207e4155, false);
var d207e4166 = new YAHOO.widget.TextNode("Version 0.9.14", d207e4115, false);

var objd207e4173 = {
    label: "[Release Notes: Version 0.9.14]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.14.html", 
    target:"contentwin"
};
var d207e4173 = new YAHOO.widget.TextNode(objd207e4173, d207e4166, false);
var d207e4177 = new YAHOO.widget.TextNode("Version 0.9.15", d207e4115, false);

var objd207e4184 = {
    label: "[Release Notes: Version 0.9.15]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.15.html", 
    target:"contentwin"
};
var d207e4184 = new YAHOO.widget.TextNode(objd207e4184, d207e4177, false);
var d207e4188 = new YAHOO.widget.TextNode("Version 0.9.16", d207e4115, false);

var objd207e4195 = {
    label: "[Release Notes: Version 0.9.16]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.16.html", 
    target:"contentwin"
};
var d207e4195 = new YAHOO.widget.TextNode(objd207e4195, d207e4188, false);
var d207e4199 = new YAHOO.widget.TextNode("Version\n            0.9.18", d207e4115, false);

var objd207e4206 = {
    label: "[Release Notes: Version 0.9.18]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.18.html", 
    target:"contentwin"
};
var d207e4206 = new YAHOO.widget.TextNode(objd207e4206, d207e4199, false);
var d207e4210 = new YAHOO.widget.TextNode("Version 0.9.19", d207e4115, false);

var objd207e4217 = {
    label: "[Release Notes: Version 0.9.19RC12]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.19.html", 
    target:"contentwin"
};
var d207e4217 = new YAHOO.widget.TextNode(objd207e4217, d207e4210, false);
var d207e4221 = new YAHOO.widget.TextNode("Version 0.9.9", d207e4115, false);

var objd207e4228 = {
    label: "[Release Notes: Version 0.9.9]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-0.9.9.html", 
    target:"contentwin"
};
var d207e4228 = new YAHOO.widget.TextNode(objd207e4228, d207e4221, false);
var d207e4232 = new YAHOO.widget.TextNode("Version 1.0.0RC00", d207e4115, false);

var objd207e4239 = {
    label: "[Release Notes: Version 1.0.0RC00 (github version)]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0.html", 
    target:"contentwin"
};
var d207e4239 = new YAHOO.widget.TextNode(objd207e4239, d207e4232, false);
var d207e4244 = new YAHOO.widget.TextNode("Version 1.0.0RC17", d207e4115, false);

var objd207e4251 = {
    label: "[Release Notes: Version 1.0.0RC17]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0RC17.html", 
    target:"contentwin"
};
var d207e4251 = new YAHOO.widget.TextNode(objd207e4251, d207e4244, false);
var d207e4255 = new YAHOO.widget.TextNode("Version 1.0.0RC19", d207e4115, false);

var objd207e4262 = {
    label: "[Release Notes: Version 1.0.0RC19]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0RC19.html", 
    target:"contentwin"
};
var d207e4262 = new YAHOO.widget.TextNode(objd207e4262, d207e4255, false);
var d207e4266 = new YAHOO.widget.TextNode("Version 1.0.0RC20", d207e4115, false);

var objd207e4273 = {
    label: "[Release Notes: Version 1.0.0RC20]",
    href: "user_docs/d4p-users-guide/release-notes/release-notes-1.0.0RC20.html", 
    target:"contentwin"
};
var d207e4273 = new YAHOO.widget.TextNode(objd207e4273, d207e4266, false);
var d207e4277 = new YAHOO.widget.TextNode("S", d207e2670, false);
var d207e4281 = new YAHOO.widget.TextNode("styles", d207e4277, false);
var d207e4290 = new YAHOO.widget.TextNode("grouped", d207e4281, false);

var objd207e4297 = {
    label: "[Specifying InDesign Grouped Style Names]",
    href: "user_docs/d4p-users-guide/dita2indesign/grouped-style-name-syntax.html", 
    target:"contentwin"
};
var d207e4297 = new YAHOO.widget.TextNode(objd207e4297, d207e4290, false);
var d207e4301 = new YAHOO.widget.TextNode("T", d207e2670, false);
var d207e4305 = new YAHOO.widget.TextNode("table of contents", d207e4301, false);
var d207e4314 = new YAHOO.widget.TextNode("generating", d207e4305, false);

var objd207e4321 = {
    label: "[html2.generate.dynamic.toc Ant parameter]",
    href: "user_docs/d4p-users-guide/html2-plugin/reference/ant-parm-generateDynamicToc.html", 
    target:"contentwin"
};
var d207e4321 = new YAHOO.widget.TextNode(objd207e4321, d207e4314, false);
var d207e4325 = new YAHOO.widget.TextNode("toolkit plugins", d207e4301, false);
var d207e4334 = new YAHOO.widget.TextNode("installing", d207e4325, false);

var objd207e4341 = {
    label: "[Installing the Toolkit Plugins]",
    href: "user_docs/d4p-users-guide/tasks/plugin-installation.html", 
    target:"contentwin"
};
var d207e4341 = new YAHOO.widget.TextNode(objd207e4341, d207e4334, false);
var d207e4345 = new YAHOO.widget.TextNode("topic domains", d207e4301, false);

var objd207e4352 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e4352 = new YAHOO.widget.TextNode(objd207e4352, d207e4345, false);
var d207e4356 = new YAHOO.widget.TextNode("topics", d207e4301, false);
var d207e4365 = new YAHOO.widget.TextNode("generating InCopy articles from", d207e4356, false);

var objd207e4372 = {
    label: "[Configuring the DITA-to-InDesign Transformation]",
    href: "user_docs/d4p-users-guide/dita2indesign/generating-incopy-articles.html", 
    target:"contentwin"
};
var d207e4372 = new YAHOO.widget.TextNode(objd207e4372, d207e4365, false);
var d207e4376 = new YAHOO.widget.TextNode("processing in map\n          context", d207e4356, false);

var objd207e4383 = {
    label: "[Map-Driven Processing]",
    href: "user_docs/d4p-users-guide/map-driven-processing/map-driven-processing.html", 
    target:"contentwin"
};
var d207e4383 = new YAHOO.widget.TextNode(objd207e4383, d207e4376, false);
var d207e4387 = new YAHOO.widget.TextNode("transformation parameters", d207e4301, false);
var d207e4394 = new YAHOO.widget.TextNode("word-to-dita transformation", d207e4387, false);

var objd207e4401 = {
    label: "[Word-to-DITA XSLT Transformation Parameters]",
    href: "user_docs/d4p-users-guide/word2dita/transform-parameters.html", 
    target:"contentwin"
};
var d207e4401 = new YAHOO.widget.TextNode(objd207e4401, d207e4394, false);
var d207e4405 = new YAHOO.widget.TextNode("transformation scenario", d207e4301, false);

var objd207e4412 = {
    label: "[Generating EPUBs From OxygenXML]",
    href: "user_docs/d4p-users-guide/epub-plugin/generating-epubs-from-oxygen.html", 
    target:"contentwin"
};
var d207e4412 = new YAHOO.widget.TextNode(objd207e4412, d207e4405, false);
var d207e4416 = new YAHOO.widget.TextNode("troubleshooting", d207e4301, false);

var objd207e4423 = {
    label: "[Troubleshooting the Word-to-DITA Process]",
    href: "user_docs/d4p-users-guide/word2dita/troubleshooting-word2dita.html", 
    target:"contentwin"
};
var d207e4423 = new YAHOO.widget.TextNode(objd207e4423, d207e4416, false);
var d207e4427 = new YAHOO.widget.TextNode("tutorials", d207e4301, false);
var d207e4436 = new YAHOO.widget.TextNode("word-to-DITA video tutorial", d207e4427, false);

var objd207e4443 = {
    label: "[Word-to-DITA Style-to-Tag Mapping Video Tutorial]",
    href: "user_docs/d4p-users-guide/word2dita/word2dita-video-tutorial-01.html", 
    target:"contentwin"
};
var d207e4443 = new YAHOO.widget.TextNode(objd207e4443, d207e4436, false);
var d207e4447 = new YAHOO.widget.TextNode("Typefi", d207e4301, false);

var objd207e4454 = {
    label: "[The DITA-to-InDesign Transformation Framework]",
    href: "user_docs/d4p-users-guide/dita2indesign/dita-to-indesign-framework-chapter.html", 
    target:"contentwin"
};
var d207e4454 = new YAHOO.widget.TextNode(objd207e4454, d207e4447, false);
var d207e4458 = new YAHOO.widget.TextNode("V", d207e2670, false);
var d207e4462 = new YAHOO.widget.TextNode("verse domain", d207e4458, false);

var objd207e4469 = {
    label: "[Topic Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/topic-domains-overview.html", 
    target:"contentwin"
};
var d207e4469 = new YAHOO.widget.TextNode(objd207e4469, d207e4462, false);
var d207e4473 = new YAHOO.widget.TextNode("vocabulary", d207e4458, false);

var objd207e4480 = {
    label: "[The DITA For Publishers Markup Vocabulary]",
    href: "user_docs/d4p-users-guide/vocabulary-part/vocabulary-part.html", 
    target:"contentwin"
};
var d207e4480 = new YAHOO.widget.TextNode(objd207e4480, d207e4473, false);
var d207e4484 = new YAHOO.widget.TextNode("vocabulary modules", d207e4458, false);
var d207e4493 = new YAHOO.widget.TextNode("domain", d207e4484, false);

var objd207e4500 = {
    label: "[DITA For Publishers Domains]",
    href: "user_docs/d4p-users-guide/vocabulary-part/domain-modules-overview.html", 
    target:"contentwin"
};
var d207e4500 = new YAHOO.widget.TextNode(objd207e4500, d207e4493, false);
var d207e4504 = new YAHOO.widget.TextNode("W", d207e2670, false);
var d207e4508 = new YAHOO.widget.TextNode("word-to-dita Toolkit plugin", d207e4504, false);
var d207e4517 = new YAHOO.widget.TextNode("Ant script for", d207e4508, false);

var objd207e4524 = {
    label: "[Setting Up an Ant Script for Running the Word-to-DITA Transform]",
    href: "user_docs/d4p-users-guide/word2dita/word-to-dita-ant-task.html", 
    target:"contentwin"
};
var d207e4524 = new YAHOO.widget.TextNode(objd207e4524, d207e4517, false);
var d207e4528 = new YAHOO.widget.TextNode("word-to-DITA transform", d207e4504, false);
var d207e4537 = new YAHOO.widget.TextNode("video tutorial", d207e4528, false);

var objd207e4544 = {
    label: "[Word-to-DITA Style-to-Tag Mapping Video Tutorial]",
    href: "user_docs/d4p-users-guide/word2dita/word2dita-video-tutorial-01.html", 
    target:"contentwin"
};
var d207e4544 = new YAHOO.widget.TextNode(objd207e4544, d207e4537, false);
var d207e4548 = new YAHOO.widget.TextNode("Word-to-DITA transform", d207e4504, false);
var d207e4557 = new YAHOO.widget.TextNode("from OxygenXML", d207e4548, false);

var objd207e4564 = {
    label: "[Generating DITA From Within OxygenXML]",
    href: "user_docs/docx2dita_guide_and_reference/word2dita-from-oxygen.html", 
    target:"contentwin"
};
var d207e4564 = new YAHOO.widget.TextNode(objd207e4564, d207e4557, false);
var d207e4568 = new YAHOO.widget.TextNode("troubleshooting", d207e4548, false);

var objd207e4575 = {
    label: "[Troubleshooting the Word-to-DITA Process]",
    href: "user_docs/d4p-users-guide/word2dita/troubleshooting-word2dita.html", 
    target:"contentwin"
};
var d207e4575 = new YAHOO.widget.TextNode(objd207e4575, d207e4568, false);
var d207e4579 = new YAHOO.widget.TextNode("Word-to-DITA transformation framework", d207e4504, false);
var d207e4588 = new YAHOO.widget.TextNode("Open Toolkit plugin for", d207e4579, false);

var objd207e4595 = {
    label: "[Generating DITA from Documents (Word-to-DITA Transformation Framework)]",
    href: "user_docs/d4p-users-guide/word2dita/word-to-dita-plugin.html", 
    target:"contentwin"
};
var d207e4595 = new YAHOO.widget.TextNode(objd207e4595, d207e4588, false);
var d207e4599 = new YAHOO.widget.TextNode("X", d207e2670, false);
var d207e4603 = new YAHOO.widget.TextNode("XSLT mode", d207e4599, false);
var d207e4612 = new YAHOO.widget.TextNode("additional-graphic-refs", d207e4603, false);

var objd207e4619 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e4619 = new YAHOO.widget.TextNode(objd207e4619, d207e4612, false);
var d207e4623 = new YAHOO.widget.TextNode("generate-graphic-map", d207e4603, false);

var objd207e4630 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e4630 = new YAHOO.widget.TextNode(objd207e4630, d207e4623, false);
var d207e4634 = new YAHOO.widget.TextNode("gmap:get-graphic-refs", d207e4603, false);

var objd207e4641 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e4641 = new YAHOO.widget.TextNode(objd207e4641, d207e4634, false);
var d207e4645 = new YAHOO.widget.TextNode("gmap:get-output-url", d207e4603, false);

var objd207e4652 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e4652 = new YAHOO.widget.TextNode(objd207e4652, d207e4645, false);
var d207e4656 = new YAHOO.widget.TextNode("map2graphicmap:handleImageListFile", d207e4603, false);

var objd207e4663 = {
    label: "[Graphic Map Generation]",
    href: "user_docs/d4p-users-guide/map-driven-processing/graphic-map-generation.html", 
    target:"contentwin"
};
var d207e4663 = new YAHOO.widget.TextNode(objd207e4663, d207e4656, false);

      
      tree.draw(); 
      } 
      
      YAHOO.util.Event.addListener(window, "load", treeInit);       
    